sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: xu577525866
  alioss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    access-key-secret: NCHXWVWsJkyArbmpqoTJKSpgQtk8BT
    access-key-id: LTAI5t8P4rJdVfEd8Di7e7LD
    bucket-name: xucheng-sky-takeout
  redis:
    host: localhost
    port: 6379
    database: 0
  wechat:
    appid: wx8cb68e1fbe9b9818
    secret: d8d024c7533948565a3032c666608259
